#!/usr/bin/env php
<?php
use AdventOfCode\Day1\NotQuiteLisp;

require_once __DIR__ . "/../vendor/autoload.php";

$input = file_get_contents(__DIR__ . "/../res/Day1/input");

$notQuiteLisp = new NotQuiteLisp();
$notQuiteLisp->move($input);

echo "Floor reached: " . $notQuiteLisp->getFloor() . PHP_EOL;
echo "First time into basement: " . $notQuiteLisp->getFirstBasementMove() . PHP_EOL;
