#!/usr/bin/env php
<?php
ini_set('memory_limit', -1);

use AdventOfCode\Day24\PresentArranger;

require_once __DIR__ . "/../vendor/autoload.php";

$presentWeights = array_map('trim', (file(__DIR__ . "/../res/Day24/input")));

$presentArranger = new PresentArranger();
$presentArranger->addPresents($presentWeights);

echo "Quantum Entanglement of first present group (3 groups): " . $presentArranger->findLowestQuantumEntaglementOfFirstGroup(3) . PHP_EOL;
echo "Quantum Entanglement of first present group (4 groups): " . $presentArranger->findLowestQuantumEntaglementOfFirstGroup(4) . PHP_EOL;
