#!/usr/bin/env php
<?php

use AdventOfCode\Day22\Boss;
use AdventOfCode\Day22\Spells\Drain;
use AdventOfCode\Day22\Spells\MagicMissile;
use AdventOfCode\Day22\Spells\Poison;
use AdventOfCode\Day22\Spells\Recharge;
use AdventOfCode\Day22\Spells\Shield;
use AdventOfCode\Day22\Wizard;
use AdventOfCode\Day22\WizardSimulator;

require_once __DIR__ . "/../vendor/autoload.php";

$wizardSimulator = new WizardSimulator();

//$wizardSimulator->addWizard(new Wizard(50, 500));
//$wizardSimulator->addBoss(new Boss(55, 8));

$wizardSimulator->addWizard(new Wizard(10, 250));
$wizardSimulator->addBoss(new Boss(14, 8));

$wizardSimulator->addAvailableSpell(new MagicMissile());
$wizardSimulator->addAvailableSpell(new Drain());
$wizardSimulator->addAvailableSpell(new Shield());
$wizardSimulator->addAvailableSpell(new Poison());
$wizardSimulator->addAvailableSpell(new Recharge());

$cheapestBattleWin = $wizardSimulator->findCheapestWayForWizardToWinBattle();
echo "Least amount of Mana you can spend and still win: " . $cheapestBattleWin . PHP_EOL;

$mostExpensiveBattleLose = $wizardSimulator->findMostExpensiveWayForWizardToLoseBattle();
echo "Most amount of Mana you can spend and still lose: " . $mostExpensiveBattleLose;
