#!/usr/bin/env php
<?php

use AdventOfCode\Day22\Boss;
use AdventOfCode\Day22\Spells\Drain;
use AdventOfCode\Day22\Spells\MagicMissile;
use AdventOfCode\Day22\Spells\Poison;
use AdventOfCode\Day22\Spells\Recharge;
use AdventOfCode\Day22\Spells\Shield;
use AdventOfCode\Day22\Wizard;
use AdventOfCode\Day22\WizardSimulator;

require_once __DIR__ . "/../vendor/autoload.php";

$wizardSimulator = new WizardSimulator();

$wizardSimulator->addAvailableSpell(new MagicMissile());
$wizardSimulator->addAvailableSpell(new Drain());
$wizardSimulator->addAvailableSpell(new Shield());
$wizardSimulator->addAvailableSpell(new Poison());
$wizardSimulator->addAvailableSpell(new Recharge());

//$wizardSimulator->setWizard(new Wizard(50, 500, false));
//$wizardSimulator->setBoss(new Boss(55, 8));
//
//$cheapestBattleWin = $wizardSimulator->findCheapestWayForWizardToWinBattle();
//echo "Least amount of Mana you can spend and still win: " . $cheapestBattleWin . PHP_EOL;

$wizardSimulator->setWizard(new Wizard(50, 500, true));
$wizardSimulator->setBoss(new Boss(55, 8));

try {
    $cheapestBattleWin = $wizardSimulator->findCheapestWayForWizardToWinBattle();
    echo "Least amount of Mana you can spend and still win in hard mode: " . $cheapestBattleWin . PHP_EOL;
} catch (Exception $e) {
    echo "Got here, not really sure how..." . PHP_EOL;
}
