#!/usr/bin/env php
<?php
use AdventOfCode\Day8\Matchsticks;

require_once __DIR__ . "/../vendor/autoload.php";

$strings = array_map('trim', file(__DIR__ . "/../res/Day8/input"));

$matchsticks = new Matchsticks();

foreach ($strings as $string) {
    $matchsticks->addString($string);
}

echo "Total difference between encoded and decoded strings: " . $matchsticks->getDifferenceInCharactersForDecodedStrings() . PHP_EOL;
echo "Total difference between doubly-encoded and encoded strings: " . $matchsticks->getDifferenceInCharactersForEncodedStrings() . PHP_EOL;
