#!/usr/bin/env php
<?php
use AdventOfCode\Day10\LookAndSay;

require_once __DIR__ . "/../vendor/autoload.php";

$input = trim(file_get_contents(__DIR__ . "/../res/Day10/input"));

$lookAndSay = new LookAndSay();

$output = $lookAndSay->lookAndSay($input, 40);

echo "After 40 iterations: " . $output . PHP_EOL;
echo "Length: " . strlen($output) . PHP_EOL;
