#!/usr/bin/env php
<?php
use AdventOfCode\Day2\WrappingPaper;
use AdventOfCode\Day2\Present;

require_once __DIR__ . "/../vendor/autoload.php";

$presentsArray = file(__DIR__ . "/../res/Day2/input");

$wrappingPaper = new WrappingPaper();

foreach ($presentsArray as $presentDimensions) {
    $wrappingPaper->addPresent(new Present($presentDimensions));
}

echo "Wrapping paper area required: " . $wrappingPaper->getRequiredWrappingPaper() . " square feet" . PHP_EOL;
echo "Ribbon required: " . $wrappingPaper->getRequiredRibbonLength() . " feet" . PHP_EOL;
