#!/usr/bin/env php
<?php

use AdventOfCode\Day5\NiceStringFinder;

require_once __DIR__ . "/../vendor/autoload.php";

$strings = array_map('trim', file(__DIR__ . "/../res/Day5/input"));

$niceStringFinder = new NiceStringFinder();

foreach ($strings as $string) {
    $niceStringFinder->addString($string);
}

echo "Number of nice strings: " . $niceStringFinder->getNumberOfNiceStrings() . PHP_EOL;
echo "Number of naughty strings: " . $niceStringFinder->getNumberOfNaughtyStrings() . PHP_EOL;

echo "Number of nice strings in new model: " . $niceStringFinder->getNumberOfNiceStringsInNewModel() . PHP_EOL;
echo "Number of naughty strings in new model: " . $niceStringFinder->getNumberOfNaughtyStringsInNewModel() . PHP_EOL;
